name: "Continuous Integration"
on:
    push:
    pull_request:

jobs:
    tests:
        name: "CI (PHP ${{ matrix.php-version }} on ${{ matrix.os }})"
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ "ubuntu-latest" ]
                php-version: [ "7.3", "7.4", "8.0" ]
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  coverage: "pcov"
                  extensions: "json"
                  php-version: "${{ matrix.php-version }}"
                  tools: "composer:v2"

            - name: "Get composer cache directory"
              id: "composercache"
              run: 'echo "::set-output name=dir::$(composer config cache-files-dir)"'

            - name: "Cache composer dependencies"
              uses: "actions/cache@v2"
              with:
                  path: "${{ steps.composercache.outputs.dir }}"
                  key: "${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}"
                  restore-keys: "${{ runner.os }}-composer-"

            - name: "Install Composer dependencies"
              run: |
                composer install --no-progress --prefer-dist --optimize-autoloader

            - name: "Run unit tests"
              run: "vendor/bin/phpunit --verbose --coverage-text"
