name: "Continuous Integration"
on:
    push:
        branches: ['master']
    pull_request:
        branches: ['*']

jobs:
    tests:
        name: "CI (PHP ${{ matrix.php-version }})"
        runs-on: "ubuntu-22.04"

        strategy:
            matrix:
                php-version:
                    - "8.2"
                    - "8.3"
#                    - "8.4"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  coverage: "pcov"
                  extensions: "json"
                  php-version: "${{ matrix.php-version }}"
                  tools: "composer:v2"

            - name: "Cache Composer dependencies"
              uses: "actions/cache@v4"
              with:
                  path: "~/.composer/cache"
                  key: "php-composer-locked-${{ hashFiles('composer.lock') }}"
                  restore-keys: "php-composer-locked-"

            - name: "Install Composer dependencies"
              run: |
                composer install --no-progress --prefer-dist --optimize-autoloader

            - name: "Run functional tests"
              run: "composer test"

            - name: "Run static code analysis"
              run: "composer analyze"
